### PR TITLE
Fix Phone Number Validation

### LINKED ISSUE #244: [PE-D][Tester B] Application accepts unrealistic one-digit phone numbers when adding/editing contacts
The application allows contacts to be created or edited with a one-digit phone number (e.g. p/1),
which is not a realistic phone number format for the product’s target use case.

This permits invalid contact data to be stored, reducing the reliability of the contact management system.

Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by nvdchw**
Updated Phone Number Validation
- Must be between 3 and 5 characters
- Must contain at least 1 digit
- First character must be a digit or a plus (+)
- Remaining characters may be digits, plus, spaces, or hyphens

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -10,19 +10,22 @@
...
-     * - (?=.{1," + MAX_LENGTH + "}$) : total length must be between 1 and MAX_LENGTH
-     * - (?=.*\\d)                    : must contain at least one digit (rejects only symbols/spaces)
-     * - [0-9+ -]+                    : allows only digits, plus, spaces, and hyphens
+     * - (?=.{MIN_LENGTH,MAX_LENGTH}$) : total length must be between MIN_LENGTH and MAX_LENGTH
+     * - (?=.*\\d)                     : must contain at least one digit
+     * - [0-9+]                        : first character must be a digit or plus (+)
+     * - [0-9+ -]{2,MAX_LENGTH - 1}    : remaining characters may be digits, plus, spaces, or hyphens
      */
-    public static final String VALIDATION_REGEX = "(?=.{1," + MAX_LENGTH + "}$)(?=.*\\d)[0-9+ -]+";
+    public static final String VALIDATION_REGEX = "(?=.{" + MIN_LENGTH + "," + MAX_LENGTH
```
Comment (x3BoffiNg) [inline src/main/java/seedu/address/model/person/Phone.java:27]: Good job! While I understand that this was based off what the team discussed, after looking into the regex, seems like cases where phone numbers are `+---------1` would be valid, not sure if we should restrict it further to only allow 1 `+` and `-` but again there are disadvantages cause this can be overzealous 🤔

**Review by x3BoffiNg — COMMENTED** [review]
LGTM 👍 But just one clarification.

File: src/main/java/seedu/address/model/person/Phone.java (hunk 1 above)
Comment (nvdchw) [reply src/main/java/seedu/address/model/person/Phone.java:27]: Thanks for pointing this out! Yes, your example could potentially be a problematic value as a phone number. However, I think attempting to tighten phone validation to prevent inputs as such would definitely put us on the radar for being overzealous in our input validation.

Perhaps we can find a way to include showing warnings for unconventional inputs (while still allowing those inputs) in our planned enhancements?
This would allow users to have more flexibility in how they choose to save phone numbers while also alerting users about unconventional inputs to avoid accidental typos.

**Review by RaisinMoldyBread — COMMENTED** [review]
LGTM!
